'use client';
import './globals.css'
import React, { useState } from 'react';
import { ThemeProvider } from 'theme-ui';
import { StickyProvider } from 'contexts/app/app.provider';
import theme from '../theme';
import SEO from '../components/home/SEO';
import Sticky from 'react-stickynode';
import Header from '../components/home/header/Header';
import Footer from '../components/home/footer/Footer';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function RootLayout({ children }) {
  const [isSticky, setIsSticky] = useState(false);
  const handleStateChange = (status) => {
    if (status.status === Sticky.STATUS_FIXED) {
      setIsSticky(true);
    } else if (status.status === Sticky.STATUS_ORIGINAL) {
      setIsSticky(false);
    }
  };
  return (
    <ThemeProvider theme={theme}>
    <StickyProvider>
        <SEO title="Startup Landing 005" />
          <Sticky innerZ={1001} top={0} onStateChange={handleStateChange}>
            <Header className={`${isSticky ? 'sticky' : 'unSticky'}`} />
          </Sticky>
          <main
            id="content"
            sx={{
              variant: 'layout.main',
            }}
          >
          {children}
        </main>
      <Footer />
    </StickyProvider>
  </ThemeProvider>
  )
}
